services:
  dropbox:
    image: tiagovdaa/dropbox-docker:latest
    container_name: dropbox
    restart: always
    environment:
      - DBOX_UID=1000
      - DBOX_GID=1000
      - DBOX_DEBUG=true
    volumes:
      - /data/dbox:/dbox
    tty: true
    stdin_open: true
